### ISSUE TITLE
Beta branch

### ISSUE THREAD

**Issue by mkljczk** [flathub/io.itch.itch#10]
Itch.io client hasn't received updates for a long time, but there are some canary updates including security patches. It would make sense to package it in Flathub Beta repo.

**Comment by Doomsdayrs** [comment]
Where do the canaries get published?

**Comment by Doomsdayrs** [comment]
Alright, I will implement the beta branch.

**Comment by Doomsdayrs** [comment]
Implemented!

**Comment by mkljczk** [comment]
Thanks!
