### ISSUE TITLE
[Feature Request] Export shortcuts or Add to Steam feature

### ISSUE THREAD

**Issue by rawdatafeel** [flathub/io.itch.itch#3]
Would it be possible to add a way to export itch games as shortcuts (Lutris does this by creating .desktop shortcuts) or a way to add itch games directly to Steam (both Heroic Games Launcher and Lutris support this feature)?

This would be especially helpful for the games that are run through wine, but would be nice to have regardless for Linux native games as well to make shortcut management easier. 

Desktop shortcuts would allow a quick and easy way to add to front-ends like Steam, but would also allow for the option of other front-ends on Linux or allow for opening the game without needing itch open.

**Comment by joshua-stone** [comment]
Is this a feature that Itch supports? Doesn't seem like it does:

https://github.com/itchio/itch/issues/864

**Comment by rawdatafeel** [comment]
Sorry about that! I was looking on the wrong page, looks like you're right.
