### ISSUE TITLE
Runtime com.valvesoftware.Steam.Utility.gamescope is end-of-life

### ISSUE THREAD

**Issue by epic0421** [flathub/io.itch.itch#6]
![image](https://github.com/flathub/io.itch.itch/assets/85042398/a18cc6c5-5fab-4736-afdc-cee21933bee0)

**Comment by orowith2os** [comment]
Here ya go: https://github.com/flathub/io.itch.itch/pull/7

**Comment by Doomsdayrs** [comment]
Thank you @orowith2os !
